services:
  hive:
    image: apache/hive:4.0.0
    environment:
      SERVICE_NAME: hiveserver2
    ports:
      - 10000:10000
      - 10002:10002
    volumes:
      - ./script.hql:/script.hql
      - ./trace.csv:/trace.csv